name: nextgen_button

description: >
  A modern and highly customizable Flutter button widget with support for
  gradients, icons, loading states, disabled states, custom widgets, and
  flexible styling options.

version: 1.0.0

homepage: https://github.com/mowlashuvo/nextgen_button
repository: https://github.com/mowlashuvo/nextgen_button
issue_tracker: https://github.com/mowlashuvo/nextgen_button/issues

topics:
  - flutter
  - button
  - widget
  - ui
  - material-design

example:
  path: example/

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter: